### ISSUE TITLE
Matrícula de Aluno

### ISSUE THREAD

**Issue by Jardeldev** [EduPrime/app#33]
**Descrição:** Desenvolver a funcionalidade de matrícula de alunos, focando em telas para dispositivos móveis. A funcionalidade deve permitir que o administrador ou responsável pela matrícula registre novos alunos, escolha a escola, a série/ano e confirme a matrícula.

**Requisitos:** 

- Interface mobile (Ionic e Vue);
- Integração com Supabase (para armazenar as informações de matrícula);
- Fluxo de preenchimento de dados do aluno e confirmação da matrícula;
- Exibição de confirmação de matrícula.

**Comment by hermesalvesbr** [comment]
Visão geral ficou ótima na descrição, mas quais campos e tabelas no banco de dados vão ser usadas?

O layout será em tabs e qual o fluxo de matrícula? Haverá confirmação por email? Haverá tela de matrícula pendente/aprovada?

**Comment by Jardeldev** [comment]
Olá @hermesalvesbr,

Obrigado pelo feedback!

**1. Campos e Tabelas no Banco de Dados:** As seguintes tabelas e campos serão utilizados para a funcionalidade de matrícula, utilizando o sistema iEducar como referência:

**Tabela students:**

- id
- name
- birthdate
- cpf
- address
- school_id (referência à tabela escolas)
- series_id (referência à tabela series)
- classroom_id (referência à tabela turmas)
- registration_status (ex: 'pendente', 'aprovada')

**Tabela school:**

- id
- name
- address
- phone

**Tabela series:**

- id
- name
- school_id

**Tabela classroom:**

- id
- name
- series_id
- period

**2. Layout e Fluxo de Matrícula:** O layout será organizado em tabs, permitindo que os usuários naveguem facilmente entre as diferentes etapas da matrícula, que incluirão:

- Tab 1: Dados básicos
- Tab 2: Dados do endereço

**3. Confirmação por E-mail:** Sim, implementaremos uma confirmação por e-mail. Após a finalização da matrícula, um e-mail será enviado ao responsável com os detalhes da matrícula, incluindo a escola, série, turma e status.

**4. Tela de Matrícula Pendente/Aprovada:** Sim, haverá uma tela para gerenciar as matrículas pendentes e aprovadas, essa tela contará com uma Search Bar para pesquisa detalhada sobre a matrícula do aluno. As matrículas que necessitam de aprovação serão listadas, e o responsável poderá verificar o status delas (pendente ou aprovada). Essa funcionalidade permitirá uma melhor gestão das matrículas no sistema.

Se houver mais alguma dúvida ou se precisar de mais informações, fico à disposição!

Obrigado, @hermesalvesbr

**Comment by Jardeldev** [comment]
https://github.com/EduPrime/app/commit/d61497b32e48ca7ff2561f9fee2d8ad0878abb01
