### ISSUE TITLE
Pré-Matrícula - Tabela Enrollment

### ISSUE THREAD

**Issue by alan-cleveston** [EduPrime/app#36]
Campos necessários:

- [x] Status; (Ativo, Inativo)
- [x] Número de matrícula; (Deve ser unique no banco de dados)
- [x] Aluno; (M2O)
- [x] Escola; (M2O)
- [x] Turma; (M2O)
        - Série e Curso estão relacionados com turma não precisa repetir relacionamento com matrícula.
- [x] Turno;
- [x] Data de matrícula; (Deve respeitar período de pré-matriculas e matrículas do ano letivo)
- [x] Data de Enturmação;
- [x] Situação (Pendente, Cursando, Aprovado, Aprovado pelo Conselho, Aprovado com Dependência, Reprovado, Transferido, Abandono e  Falecido)

**Comment by alan-cleveston** [comment]
Matrícula possui algumas movimentações que no i-Educar são criadas tabelas auxiliares exemplo matricula_turma, que faz a junção das informações do aluno com a informação da turma, pois no decorrer do ano letivo o aluno pode ser remanejado entre outras turmas da mesma escola e pode ser transferido para outra escola.


Alguma sugestão para realizarmos isso de forma diferente ? ou realizamos da mesma forma?
![image](https://github.com/user-attachments/assets/50863e87-d30e-4e35-b9fe-ba9ae5b96469)

**Comment by hermesalvesbr** [comment]
Alan no atual tem uma tabela chama enrollment. Veja se ela está bem planejada. Talvez só ela possa resolver o armazenamento dos dados.
